### ISSUE TITLE
gmcs missing

### ISSUE THREAD

**Issue by 4L3XK** [ErwinRieger/pygnc#1]
Das PyGnc aqbanking python interface kann nicht kompiliert werden mit Mono 5.18.0.240.
Seit Mono 4.0.2.5 wird **gmcs** nicht mehr mit ausgeliefert:
https://github.com/mono/mono/commit/b304ec5e0e694ef7098e0fc3eba9dbc0162f4568

```
$ sh make.sh 
# @which gmcs > /dev/null
make: *** [Makefile:46: checks] Fehler 1
```

@ErwinRieger Welche Version benutzt du?

**Comment by ErwinRieger** [comment]
Vielen dank für deinen hinweis, aber *pygnc* bzw. dessen aqbanking interface ist nicht dazu gedacht zusammen mit mono benutzt zu werden...
Ich benutze *aqbankingNET-master* nur zusammen mit python...
